apps/servicio/urls.py
from django.conf.urls import url

from apps.servicio.views import *

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login', login, name="login"),
    url(r'^mapa', mapa, name="mapa"),
    url(r'^caja', caja, name="caja"),
    url(r'^facturar$', facturar, name='facturar'),
    url(r'^vistaFacturas$', vistaFacturas, name='vistaFacturas'),
    url(r'^factura/(?P<id>[0-9]{1,})', factura, name='factura'),

]

peluqueria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.servicio.urls', namespace="servicio")),
    url(r'^contabilidad/', include('apps.contabilidad.urls', namespace="contabilidad")),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} Title {% endblock %} - Peluqueria</title>
 	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">

	<link rel="stylesheet" href="{% static 'css/material-icons.css' %}">
 	<script type="text/javascript" src="{% static 'js/fontawesome-all.js' %}"></script>
 	{% block extrahead %}
	{% endblock %}
 	<link rel="stylesheet" href="{% static 'css/myStyles.css' %}">
</head>
<body>
 	{% block navbar %}
		{% include 'base/navbar.html' %}
	{% endblock %}

	<main>
		{% block content %}
			<h4>Soy el contenido</h4>
		{% endblock %}
	</main>
 	{% block footer %}
		{% include 'base/footer.html' %}
	{% endblock %}

	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/myScript.js' %}"></script>
 	{% block extrajs %}
	{% endblock %}
</body>
</html>

templates/base/footer.html
<footer class="page-footer teal darken-1">
	<div class="container">
		<div class="row">
            <div class="col s12 m6 l8">
				<h3><i class="fas fa-cut"></i> Peluqueria</h3>
				<big>Somos una peluquería fundada hace 8 años . Ofrecemos a nuestros clientes servicios de salud, belleza y bienestar, a través de servicios de estética y peluquería con altos estándares de calidad , apoyados en un equipo competente y efectivo.</big>
            </div>
			<div class="col s12 m6 offset-l1 l3">
                <h4>Developers</h4>
				<a href="https://github.com/ibanb04" class="white-text oscurecer">
					<i class="fab fa-github fa-2x"></i> <big>Ivan Bettin</big>
				</a>
				<br>
                <a href="https://github.com/samir04m" class="white-text oscurecer">
					<i class="fab fa-github fa-2x"></i> <big>Samir Mejia</big>
				</a>
				<br>
				<a href="https://github.com/Adal1013" class="white-text oscurecer">
					<i class="fab fa-github fa-2x"></i> <big>Adalberto Avila</big>
				</a>
            </div>
		</div>
	</div>
	<div class="footer-copyright white-text">
		<div class="container">
			<span class="oscurecer">All Rights Reserved © 2018</span>
			<a class="grey-text text-lighten-4 right oscurecer" href="http://materializecss.com/">Power By MaterializeCss</a>
		</div>
	</div>

</footer>

templates/base/navbar.html
<!-- <header> -->
<div class="navbar-fixed">
	<nav>
	    <div class="nav-wrapper teal">
	      	<div class="container">
	      		<a href="{% url 'servicio:home' %}" class="brand-logo truncate" style="margin-left: 20px;">
					<i class="fas fa-cut"></i> Peluqueria
				</a>

				<a href="#" data-activates="mobile" class="button-collapse">
					<i class="material-icons">menu</i>
				</a>

	      		<ul class="right hide-on-med-and-down">
		        	<li><a href="{% url 'servicio:home' %}" id="ainicio"><big>Inicio</big></a></li>
		        	<li><a href="{% url 'servicio:mapa' %}" id="amenu" ><big>Mapa</big></a></li>

	      		</ul>
	      		<ul class="side-nav" id="mobile">
		        	<li><a href="{% url 'servicio:home' %}">Inicio</a></li>
					<li><a href="{% url 'servicio:mapa' %}">Mapa</a></li>
	      		</ul>
	      	</div>
	    </div>
	</nav>
</div>
<!-- </header> -->