apps/contabilidad/urls.py
from django.conf.urls import url

from apps.contabilidad.views import *

urlpatterns = [
    url(r'^$', reportes, name="reportes"),
    url(r'^egresos', egresos, name="egresos"),
    url(r'^egreso/(?P<id>[0-9]{1,})', egreso, name='egreso'),
    # url(r'^reportes', reportes, name="reportes"),
    url(r'^reportes-diarios', reportes_diarios, name="reportes_diarios"),
    url(r'^reportes-semanales', reportes_semanales, name="reportes_semanales"),
    url(r'^reportes-mensuales', reportes_mensuales, name="reportes_mensuales"),
    url(r'^reportes-mensuales', reportes_mensuales, name="reportes_mensuales"),
    url(r'^reportes-por-servicios', reportes_por_servicios, name="reportes_por_servicios"),
    url(r'^reportes-por-empleados', reportes_por_empleados, name="reportes_por_empleados"),

]

apps/servicio/urls.py
from django.conf.urls import url

from apps.servicio.views import *

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login', login, name="login"),
    url(r'^mapa', mapa, name="mapa"),
    url(r'^caja', caja, name="caja"),
    url(r'^facturar$', facturar, name='facturar'),
    url(r'^vistaFacturas$', vistaFacturas, name='vistaFacturas'),
    url(r'^factura/(?P<id>[0-9]{1,})', factura, name='factura'),

]

peluqueria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.servicio.urls', namespace="servicio")),
    url(r'^contabilidad/', include('apps.contabilidad.urls', namespace="contabilidad")),
]

apps/servicio/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Empleado(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)

    def __str__(self):
        return "{} - {} {}".format(self.id, self.nombre, self.apellidos)

    def fname(self):
        return "{} {}".format(self.nombre, self.apellidos)

class Servicio(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "{} - {}".format(self.id, self.nombre)

class Tipo(models.Model):
    nombre = models.CharField(max_length=50)
    servicio = models.ForeignKey(Servicio, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.id, self.nombre)

class Subtipo(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    tipo = models.ForeignKey(Tipo, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {} - {} - {}".format(self.id, self.nombre, self.tipo.nombre, self.tipo.servicio.nombre)

    def name(self):
        return "{} {}".format(self.tipo.nombre, self.nombre)

class Factura(models.Model):
    empleado = models.ForeignKey(Empleado, null=False, blank=False, on_delete=models.CASCADE)
    subtipos = models.ManyToManyField(Subtipo)
    total =  models.IntegerField()
    day =  models.IntegerField()
    month =  models.IntegerField()
    year =  models.IntegerField()
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "Factura #{} - {}. $ {} - Fecha {}/{}/{}".format(self.id, self.empleado.fname(),
                        self.total, self.day, self.month, self.year)

templates/main/caja.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Caja Registradora{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 offset-m1 m10">
                <div class="card-panel hoverable z-depth-2">
                    <h3>Caja Registradora</h3>
                    <form action="{% url 'servicio:facturar' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col s12 m6">
                                <h5 class="m-l-10">Seleccione un empleado:</h5>
                                <div class="m-l-20">
                                    {% if empleados %}
                                        {% for empleado in empleados %}
                                          <p>
                                            <input name="empleado" type="radio" value="{{ empleado.id }}" id="{{ empleado.id }}" />
                                            <label for="{{ empleado.id }}">{{ empleado.nombre }} {{ empleado.apellidos }}</label>
                                          </p>
                                        {% endfor %}
                                    {% else %}
                                        <h4>No hay empleados :(</h4>
                                    {% endif %}
                                </div>
                            </div>

                            <!-- <div class="input-field col s12 m6">
                              <select name="empleado">
                                  {% if empleados %}
                                      <option value="" disabled selected>Seleccione un empleado</option>
                                      {% for empleado in empleados %}
                                          <option value="{{ empleado.id }}">{{ empleado.nombre }} {{ empleado.apellidos }}</option>
                                      {% endfor %}
                                      {% else %}
                                          <h4>No hay empleados :(</h4>
                                  {% endif %}
                              </select>
                              <label>Empleado</label>
                          </div> -->


                            <div class="col s12 m6">
                                {% if servicios %}
                                    <ul class="collapsible" data-collapsible="accordion">
                                        {% for servicio in servicios %}
                                        <li>
                                            <div class="collapsible-header active">{{ servicio.nombre }}</div>
                                            <div class="collapsible-body p-0">

                                                    <ul class="collapsible m-0" data-collapsible="accordion">
                                                        {% for tipo in servicio.tipo_set.all %}
                                                            <li>
                                                                <div class="collapsible-header grey lighten-4">{{ tipo.nombre }}</div>
                                                                <div class="collapsible-body p-tb-10 grey lighten-5">
                                                                    {% for subtipo in tipo.subtipo_set.all %}
                                                                    <p>
                                                                        <input name="{{ tipo.nombre }}" type="radio" value="{{ subtipo.id }}" id="subtipo-{{ subtipo.id }}"/>
                                                                        <label for="subtipo-{{ subtipo.id }}">{{ subtipo.nombre }} - {{ subtipo.precio }}</label>
                                                                   </p>
                                                                   {% endfor %}
                                                                </div>
                                                            </li>
                                                        {% endfor %}
                                                    </ul>

                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <h4>No hay servicios :(</h4>
                                {% endif %}

                            </div>
                            <div class="col s12">
                                <br>
                                <!-- <big>Total a Pagar: $ 120.000 COP</big> -->
                                <center><button type="submit" class="btn waves-effect waves-light btn-rounded">Generar Factura</button></center>
                            </div>

                        </div>
                    </form>

                </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/main/egreso.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} Vista Egreso {% endblock %}

{% load indice %}

{% block content %}
    <div class="container">
        <br>
        <div class="row m-b-0">
            <a href="{% url 'contabilidad:egresos' %}" class="white-text">
                <big><i class="fas fa-arrow-left"></i> Volver al Panel de Egresos</big>
            </a>
        </div>
        <div class="row">
            <div class="col s12 offset-m2 m8">
                <div class="card-panel">
                    {% if egreso %}
                        <center><h4 style="margin-top:0px;">Egresos de  {{ meses|indice:egreso.month }} </h4></center>
                        <table class="striped bordered highlight responsive-table">
                            <thead>
                                <tr>
                                    <th>Gasto</th>
                                    <th>Valor</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Insumos de Materia Prima</td>
                                    <td>$ {{egreso.insumos}}</td>
                                </tr>
                                <tr>
                                    <td>Compra y reparación de Instrumentación</td>
                                    <td>$ {{egreso.instrumentacion}}</td>
                                </tr>
                                <tr>
                                    <td>Alquiler del local comercial</td>
                                    <td>$ {{egreso.alquiler}}</td>
                                </tr>
                                <tr>
                                    <td>Pago de Servicios públicos</td>
                                    <td>
                                        Energia: $ {{egreso.energia}} <br>
                                        Agua: $ {{egreso.agua}} <br>
                                        Telefonía: $ {{egreso.telefonia}} <br>
                                        Total: $ {{egreso.totalServiciosPublicos}}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="right-align">
                            <h5>Egreso Total: $ {{totalEgreso}}</h5>
                        </div>

                    {% else %}
                        <center>
                            <h3>:(</h3>
                            <h4>Egreso no encontrado</h4>
                        </center>
                    {% endif %}
                
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>
{% endblock %}

templates/main/egresos.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Egresos{% endblock %}

{% load indice %}
{% load matriz %}

{% block content %}
    <div class="container">
        <br>
        <div class="row m-b-0">
            <a href="{% url 'contabilidad:reportes' %}" class="white-text">
                <big><i class="fas fa-arrow-left"></i> Volver al Panel de contabilidad</big>
            </a>
        </div>
        <div class="card-panel">
            <div class="row">
                {% if egresosDelMes %}
                        <div class="col s12 m8">
                            <center><h4 style="margin-top:0px;">Egresos de  {{ meses|indice:egresosDelMes.month }} </h4></center>
                            <table class="striped bordered highlight responsive-table">
                                <thead>
                                    <tr>
                                        <th>Gasto</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Insumos de Materia Prima</td>
                                        <td>$ {{egresosDelMes.insumos}}</td>
                                    </tr>
                                    <tr>
                                        <td>Compra y reparación de Instrumentación</td>
                                        <td>$ {{egresosDelMes.instrumentacion}}</td>
                                    </tr>
                                    <tr>
                                        <td>Alquiler del local comercial</td>
                                        <td>$ {{egresosDelMes.alquiler}}</td>
                                    </tr>
                                    <tr>
                                        <td>Pago de Servicios públicos</td>
                                        <td>
                                            Energia: $ {{egresosDelMes.energia}} <br>
                                            Agua: $ {{egresosDelMes.agua}} <br>
                                            Telefonía: $ {{egresosDelMes.telefonia}} <br>
                                            Total: $ {{egresosDelMes.totalServiciosPublicos}}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                            <h5 class="right">Egreso Total: $ {{totalEgreso}}</h5>
                        </div>

                        <div class="col s12 m4">
                            <div class="m-l-20" style="line-height:2;">
                                <big><b>Egresos de otros meses</b></big>
                                <br>
                                <div class="m-l-20">
                                    {% if egresos %}
                                        {% for e in egresos %}
                                            <a href="{% url 'contabilidad:egreso' e.id %}">Egresos {{meses|indice:e.month}} del {{e.year}}</a> <br>
                                        {% endfor %}
                                    {% else %}
                                        No hay egresos para mostrar
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                {% else %}
                    <center>
                        <h5>Aun no se definen los egresos de este mes</h5>
                    </center>
                {% endif %}
            </div>
            <div class="row">
                <div id="curve_chart" style="height: 500px"></div>
            </div>

        </div>
    </div>

{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Meses', 'Valor del egreso'],
          {% for dato in datosGrafica %}
              [ '{{ dato|matriz:0 }}', {{ dato|matriz:1 }}],
          {% endfor %}
        ]);

        var options = {
          title: 'Egresos de los ultimos meses',
          curveType: 'function',
          legend: { position: 'bottom' },
          vAxis: {title: 'Capital'},
          hAxis: {title: 'Meses'}
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
{% endblock %}

templates/main/factura.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Factura{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <br>
        <div class="row m-b-0">
            <a href="{% url 'servicio:caja' %}" class="white-text">
                <big><i class="fas fa-arrow-left"></i> Ir a caja registradora</big>
            </a>
        </div>
        <div class="row">
            <div class="col s12 offset-m2 m8">
                <div class="card-panel" style="font-size:18px;">
                    {% if factura %}
                    <h4>Factura de Pago #{{ factura.id }}</h4>
                    <hr>
                    <div class="row">
                        <div class="col s12">
                            <b>Fecha:</b>
                            <div class="right">{{ factura.fecha }}</div>
                        </div><br><br>
                        <div class="col s12">
                            <b>Empleado:</b>
                            <div class="right">{{ factura.empleado.fname }}</div>
                        </div><br><br>
                        <div class="col s12">
                            <b>Servicios:</b>
                            <div class="p-l-10">
                                <ol>
                                    {% for s in factura.subtipos.all %}
                                        <li>{{s.tipo.nombre}} - {{s.nombre}} <div class="right">$ <span>{{s.precio}}</span></div></li>
                                    {% endfor %}
                                </ol>
                            </div>
                        </div><br>
                        <div class="col s12">
                            <div class="right">Total: $ <span id="total">-</span></div>
                        </div>

                    </div>
                    {% else %}
                        <center>
                            <h2>:(</h2>
                            <h4>No se ha encontrado la factura</h4>
                        </center>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript">
        $(document).ready(function() {
            var total = 0;
            $('li > div > span').each(function(index){
                var precio = parseInt($(this).text());
                total = total + precio;
            });

            $('span#total').text(total);

        });

    </script>
{% endblock %}

templates/main/mapa.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Reportes{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <br>
        <div class="row">
            <div class="col s12 offset-m2 m8">
                <div class="card-panel">
                    <center><h4>Mapa del Sitio</h4></center>
                    <hr><br>
                    <div class="row">
                        <div class="col s12 offset-m1 m10" style="font-size: 20px;">
                            <a href="{% url 'servicio:home' %}" class="blue-text">
                                <i class="fas fa-home"></i> Pagina de Inicio</a>
                            <br><br>
                            <a href="{% url 'servicio:caja' %}" class="blue-text">
                                <i class="far fa-list-alt"></i> Caja Registradora</a>
                            <br><br>
                            <a href="{% url 'servicio:vistaFacturas' %}" class="blue-text">
                                <i class="fas fa-clipboard-list"></i> Registro de Facturas</a>
                            <br><br>
                            <a href="{% url 'contabilidad:reportes' %}" class="blue-text">
                                <i class="fas fa-chart-line"></i> Area de Contabilidad</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/reporte.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}{{title}}{% endblock %}

{% block extrahead %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static "" %}{{archivo}}"></script>

    <style>
        body {
            background-color: #00796b;
        }
    </style>
{% endblock %}

{% block content %}
    <br>
    <div class="container">
        <div class="card-panel" style="overflow:hidden;">
            <center><h4 class="m-t-0">{{title}}</h4></center>
            <hr>
            <div id="chart_div"></div>
        </div>
    </div>

{% endblock %}

templates/main/reportes.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} Contabilidad {% endblock %}

{% load matriz %}
{% load nombre_mes %}

{% block content %}
    <br>
    <div class="container">
        <div class="card-panel z-depth-4">
            <center><h4 style="margin-top:0px;">Panel de Contabilidad</h4></center> <hr>
            <div class="row">
                <div class="col s12 m6" style="font-size:26px;">
                    Total de Ingresos:
                    <div class="p-l-20">
                        <ul class="m-0">
                            <li>Dueño: <div class="right">$ <span class="v">{{ingreso.dueno}}</span></div></li>
                            <li>Empleados: <div class="right">$ <span class="v">{{ingreso.empleados}}</span></div></li>
                            <li>Insumos: <div class="right">$ <span class="v">{{ingreso.insumos}}</span></div></li>
                            <li>Total: <div class="right">$ <span id="total"> {{ingreso.total}}</span></div></li>
                        </ul>
                    </div>

                    <center>
                        <small>
                            <a href="{% url 'contabilidad:egresos' %}">Consultar Egresos</a>
                        </small>
                    </center>
                </div>
                <div class="col s12 offset-m1 m5">
                    <center><big><b>Reportes de Ingresos</b></big></center>
                    <ul style="font-size:20px;">
                        <li><a href="{% url 'contabilidad:reportes_diarios' %}">Ver Reportes Diarios</a></li>
                        <li><a href="{% url 'contabilidad:reportes_semanales' %}">Ver Reportes Semanales</a></li>
                        <li><a href="{% url 'contabilidad:reportes_mensuales' %}">Ver Reportes Mensuales</a></li>
                        <li><a href="{% url 'contabilidad:reportes_por_servicios' %}">Ver Reportes Por Servicio</a></li>
                        <li><a href="{% url 'contabilidad:reportes_por_empleados' %}">Ver Reportes Por Empleados</a></li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="row">
                <center><h4>Balance Mensual</h4></center>
                {% if datos %}
                    <div class="container">
                        <table class="bordered highlight responsive-table">
                            <thead>
                                <tr>
                                    <th>Mes</th>
                                    <th>Ingresos</th>
                                    <th>Egresos</th>
                                    <th>Ganancias</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in datos %}
                                <tr>
                                    <td>Mes de {{i|nombre_mes:0}}</td>
                                    <td>$ {{i|matriz:1}}</td>
                                    <td>$ {{i|matriz:2}}</td>
                                    <td>$ {{i|matriz:3}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                    <div class="row">
                        <br><br>
                        <center><h4>Grafica de Ingresos Vs Egresos</h4></center>
                        <div id="curve_chart2" style="height: 400px"></div>

                    </div>
                    <div class="row">
                        <hr>
                        <center><h4>Grafica de Ganancias</h4></center>
                        <div id="curve_chart" style="height: 400px"></div>
                    </div>



                {% else %}
                    <center>
                        <br><br>
                        <h5>No hay datos para mostrar</h5>
                    </center>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Meses', 'Ganancias'],
          {% for dato in datos %}
              [ '{{ dato|matriz:0 }}', {{ dato|matriz:3 }}],
          {% endfor %}
        ]);

        var options = {
          curveType: 'function',
          legend: { position: 'bottom' },
          vAxis: {title: 'Capital'},
          hAxis: {title: 'Meses'}
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));
        chart.draw(data, options);

        var data2 = google.visualization.arrayToDataTable([
          ['Meses', 'Ingresos', 'Egresos'],
          {% for dato in datos %}
              [ '{{ dato|matriz:0 }}', {{ dato|matriz:1 }}, {{ dato|matriz:2 }}],
          {% endfor %}
        ]);


        var chart2 = new google.visualization.LineChart(document.getElementById('curve_chart2'));
        chart2.draw(data2, options);
      }
    </script>
{% endblock %}

templates/main/vistaFacturas.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} Registro de Facturas {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <center><h4>Registro de Facturas</h4></center>
                    {% if facturas %}
                        <table class="striped bordered highlight responsive-table">
                            <thead>
                                <tr>
                                    <th>N° de Factura</th>
                                    <th>Fecha</th>
                                    <th>Empleado</th>
                                    <th>Pago</th>
                                    <th>Ver</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for f in facturas %}
                                    <tr>
                                        <td>{{ f.id }}</td>
                                        <td>{{ f.fecha }}</td>
                                        <td>{{ f.empleado.fname }}</td>
                                        <td>$ {{ f.total }}</td>
                                        <td>
                                            <a href="{% url 'servicio:factura' f.id %}">Ver Factura</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <center>
                            <br><br>
                            <h5>No hay facturas para mostrar</h5>
                        </center>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extrahead %}
    <style>
        body {
            background-color: #00796b;
        }
    </style>

{% endblock %}